# site title
title: GeekBoy

# user name or organization name
user: coderzhw

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 1#e0b2dc2eaa5696752bc41537db9a3e7f2074790

# posts per page
perpage: 8


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
